name: "Git Push"
description: "Action to add, commit, and push changes to a git repository"
branding:
  icon: upload-cloud
  color: blue

inputs:
  add-path:
    description: "Path to add to the git repository"
    required: false
    default: "."
  commit-message:
    description: "Commit message"
    required: true
  push-remote:
    description: "Remote to push to"
    required: false
    default: "origin"
  push-ref:
    description: "Ref to push to"
    required: false
    default: ""
  # Additional args for the git commands
  add-args:
    description: "Arguments to pass to `git add`"
    required: false
    default: ""
  commit-args:
    description: "Arguments to pass to `git commit`"
    required: false
    default: ""
  push-args:
    description: "Arguments to pass to `git push`"
    required: false
    default: ""
  # Git user information
  user-name:
    description: "Git user name"
    required: false
    default: "github-actions[bot]"
  user-email:
    description: "Git user email"
    required: false
    default: "41898282+github-actions[bot]@users.noreply.github.com"
  # Others
  github-token:
    description: "GitHub token"
    required: false
    default: ${{ github.token }}

outputs:
  head-sha:
    description: "The reference of the commit that was pushed or the current HEAD if no changes were pushed"
    value: ${{ steps.parse.outputs.head-sha }}
  committed:
    description: Whether changes were detected. The return value is in the form of a string. ("true" or "false")
    value: ${{ steps.git.outputs.committed }}

runs:
  using: composite
  steps:
    - shell: bash
      id: setup
      name: Setup Git
      run: |
        git config user.name "${{ inputs.user-name }}"
        git config user.email "${{ inputs.user-email }}"
    - shell: bash
      id: git
      name: Run Git
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "Changes detected"
          git add ${{ inputs.add-args }} ${{ inputs.add-path }}
          git commit ${{ inputs.commit-args }} -m "${{ inputs.commit-message }}"
          git push ${{ inputs.push-args }} ${{ inputs.push-remote }} ${{ inputs.push-ref }}
          echo "committed=true" >> $GITHUB_OUTPUT
        else
          echo "No changes detected"
          echo "committed=false" >> $GITHUB_OUTPUT
        fi
    - shell: bash
      id: parse
      name: Parse Git Info
      run: |
        echo "head-sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
